package com.magicsmp.magicspawners.listener;

import com.magicsmp.magicspawners.MagicSpawners;
import com.magicsmp.magicspawners.gui.SpawnerGui;
import com.magicsmp.magicspawners.model.SpawnerData;
import org.bukkit.GameMode;
import org.bukkit.Material;
import org.bukkit.block.CreatureSpawner;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.EntityType;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.event.entity.EntityExplodeEvent;
import org.bukkit.event.entity.SpawnerSpawnEvent;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.inventory.EquipmentSlot;
import org.bukkit.inventory.ItemStack;

import java.util.Map;

public final class SpawnerListener implements Listener {
    private final MagicSpawners plugin;
    public SpawnerListener(MagicSpawners plugin){this.plugin=plugin;}

    @EventHandler(priority=EventPriority.HIGH,ignoreCancelled=true)
    public void place(BlockPlaceEvent e){
        if(e.getBlockPlaced().getType()!=Material.SPAWNER)return;
        EntityType type=plugin.manager().itemType(e.getItemInHand()); if(type==null)return;
        int amount=plugin.manager().itemAmount(e.getItemInHand());
        SpawnerData existing=plugin.storage().at(e.getBlockAgainst().getLocation());
        if(existing!=null && plugin.getConfig().getBoolean("stacking.merge-on-place",true) && existing.entityType()==type && e.getPlayer().hasPermission("magicspawners.stack")){
            int max=plugin.getConfig().getInt("stacking.max-stack",2000); if(existing.stackSize()+amount>max){e.setCancelled(true);e.getPlayer().sendMessage(plugin.messages().get("stack-limit",Map.of("max",String.valueOf(max))));return;}
            e.setCancelled(true); existing.stackSize(existing.stackSize()+amount);
            if(e.getPlayer().getGameMode()!=GameMode.CREATIVE){ItemStack hand=e.getItemInHand();hand.setAmount(hand.getAmount()-1);}
            e.getPlayer().sendMessage(plugin.messages().get("stack-success",Map.of("amount",String.valueOf(existing.stackSize()))));return;
        }
        plugin.manager().register(e.getBlockPlaced().getLocation(),type,amount);
    }

    @EventHandler(ignoreCancelled=true)
    public void interact(PlayerInteractEvent e){
        if(e.getHand()!=EquipmentSlot.HAND || e.getClickedBlock()==null || e.getClickedBlock().getType()!=Material.SPAWNER)return;
        SpawnerData d=plugin.storage().at(e.getClickedBlock().getLocation());
        if(d==null && plugin.getConfig().getBoolean("convert-natural-spawners",true) && e.getClickedBlock().getState() instanceof CreatureSpawner cs){d=plugin.manager().register(e.getClickedBlock().getLocation(),cs.getSpawnedType(),1);}
        if(d==null)return;
        ItemStack held=e.getItem();
        if(held!=null && held.getType().name().endsWith("_SPAWN_EGG") && e.getPlayer().hasPermission("magicspawners.changetype")){
            EntityType type=entityFromEgg(held.getType());if(type!=null&&plugin.entities().supported().contains(type)){e.setCancelled(true);d.entityType(type);if(e.getClickedBlock().getState() instanceof CreatureSpawner cs){cs.setSpawnedType(type);cs.update(true,false);}e.getPlayer().sendMessage(plugin.messages().get("type-changed",Map.of("entity",plugin.manager().pretty(type))));return;}
        }
        // Sneaking is reserved for pickup/breaking interaction. Do not force-open the GUI while crouched.
        if(e.getPlayer().isSneaking())return;
        if(!e.getPlayer().hasPermission("magicspawners.open"))return;
        e.setCancelled(true);SpawnerGui.open(e.getPlayer(),d);
    }

    /**
     * Managed MagicSpawners are fully digital. The vanilla spawner block remains as
     * the visual/interaction block, but any attempt by Bukkit/Minecraft to spawn a
     * real entity from it is cancelled. Loot is generated by GenerationTask instead.
     */
    @EventHandler(priority=EventPriority.HIGHEST, ignoreCancelled=true)
    public void physicalSpawnerSpawn(SpawnerSpawnEvent e){
        if(!plugin.getConfig().getBoolean("digital.disable-physical-spawns",true))return;
        CreatureSpawner spawner=e.getSpawner();
        if(spawner==null)return;
        if(plugin.storage().at(spawner.getLocation())!=null)e.setCancelled(true);
    }

    @EventHandler(priority=EventPriority.HIGH, ignoreCancelled=true)
    public void breakSpawner(BlockBreakEvent e){
        if(e.getBlock().getType()!=Material.SPAWNER)return;
        SpawnerData d=plugin.storage().at(e.getBlock().getLocation());
        if(d==null)return;

        if(!plugin.getConfig().getBoolean("breaking.enabled",true)||!e.getPlayer().hasPermission("magicspawners.break")){
            e.setCancelled(true);return;
        }

        if(plugin.getConfig().getBoolean("breaking.require-sneaking",true) && !e.getPlayer().isSneaking()){
            e.setCancelled(true);
            e.getPlayer().sendMessage(plugin.messages().get("break-sneak-required"));
            return;
        }

        ItemStack tool=e.getPlayer().getInventory().getItemInMainHand();
        if(plugin.getConfig().getBoolean("breaking.silk-touch-required",true) && tool.getEnchantmentLevel(Enchantment.SILK_TOUCH)<=0){
            e.setCancelled(true);e.getPlayer().sendMessage(plugin.messages().get("break-denied"));return;
        }

        // Prevent vanilla spawner drops/XP and return the exact digital stack item.
        e.setDropItems(false);
        e.setExpToDrop(0);
        plugin.storage().remove(d);

        if(Math.random()*100.0<=plugin.getConfig().getDouble("breaking.drop-chance",100.0)){
            for (ItemStack item : plugin.manager().createItems(d.entityType(), d.stackSize())) {
                if(plugin.getConfig().getBoolean("breaking.direct-to-inventory",true)){
                    var rest=e.getPlayer().getInventory().addItem(item);
                    rest.values().forEach(i->e.getBlock().getWorld().dropItemNaturally(e.getBlock().getLocation(),i));
                } else {
                    e.getBlock().getWorld().dropItemNaturally(e.getBlock().getLocation(),item);
                }
            }
        }
    }

    @EventHandler(ignoreCancelled=true)
    public void explosion(EntityExplodeEvent e){if(!plugin.getConfig().getBoolean("breaking.explosion-protection",true))return;e.blockList().removeIf(b->b.getType()==Material.SPAWNER&&plugin.storage().at(b.getLocation())!=null);}

    private EntityType entityFromEgg(Material m){String n=m.name();if(!n.endsWith("_SPAWN_EGG"))return null;try{return EntityType.valueOf(n.substring(0,n.length()-10));}catch(Exception ex){return null;}}
}
